### ISSUE TITLE
apt-get install pythonsimplemediawiki should auto-install python-iso8601

### ISSUE THREAD

**Issue by fhocutt** [iliana/python-simplemediawiki#11]
I installed python-simplemediawiki with apt-get install on Ubuntu 14.04, which didn't raise any errors. 

When I opened python and typed "import simplemediawiki" I got the following error: 

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/simplemediawiki.py", line 36, in <module>
    import iso8601
ImportError: No module named iso8601
```

Running "sudo apt-get install python-iso8601" solved the problem, but python-simplemediawiki should auto-install needed dependencies.

**Comment by iliana** [comment]
That's a packaging problem on Ubuntu's end, not mine.

**Comment by fhocutt** [comment]
Reported to Ubuntu: https://bugs.launchpad.net/ubuntu/+source/python-simplemediawiki/+bug/1328303
